export type RepositoryFramework = 
  | 'React' 
  | 'Next.js' 
  | 'Vite'
  | 'Remix'
  | 'Astro'
  | 'Vue' 
  | 'Nuxt' 
  | 'Angular' 
  | 'Laravel' 
  | 'Express' 
  | 'NestJS' 
  | 'Node.js' 
  | 'Python' 
  | 'Django' 
  | 'Flask' 
  | 'PHP' 
  | 'WordPress' 
  | 'Static HTML';
