import React from 'react';
import { CEOExecutiveReport } from '../CEOContext';
import { FileText, CheckCircle2, AlertTriangle, ShieldCheck, Zap, Award } from 'lucide-react';

interface ExecutiveReportProps {
  report: CEOExecutiveReport;
}

export const ExecutiveReportView: React.FC<ExecutiveReportProps> = ({ report }) => {
  return (
    <div className="space-y-6 text-xs animate-fade-in">
      {/* Header Info */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-3">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-slate-100 pb-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-[#4F46E5] font-extrabold text-lg">
              👑
            </div>
            <div>
              <h2 className="text-base font-extrabold text-slate-900">Executive Technical & Growth Briefing</h2>
              <p className="text-slate-400 font-semibold">Generated by CEO Agent • Model: {report.model} ({report.provider})</p>
            </div>
          </div>

          <span className="px-3 py-1 bg-emerald-50 text-emerald-700 font-extrabold rounded-full border border-emerald-200 flex items-center gap-1">
            <Award className="w-3.5 h-3.5" />
            Confidence Score: {report.confidenceScore}%
          </span>
        </div>

        <div>
          <h4 className="font-extrabold text-slate-900 text-xs mb-1">Executive Summary</h4>
          <p className="text-slate-700 font-medium leading-relaxed bg-slate-50 p-4 rounded-xl border border-slate-100">
            {report.executiveSummary}
          </p>
        </div>
      </div>

      {/* Strengths & Weaknesses Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <div className="p-5 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-3">
          <h3 className="font-extrabold text-slate-900 flex items-center gap-2 text-sm border-b border-slate-100 pb-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            Platform Technical Strengths
          </h3>
          <ul className="space-y-2">
            {report.strengths.map((str, idx) => (
              <li key={idx} className="p-2.5 rounded-xl bg-emerald-50/50 border border-emerald-100 font-medium text-emerald-900 flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-600 mt-1.5 flex-shrink-0"></span>
                <span>{str}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Weaknesses */}
        <div className="p-5 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-3">
          <h3 className="font-extrabold text-slate-900 flex items-center gap-2 text-sm border-b border-slate-100 pb-2">
            <AlertTriangle className="w-4 h-4 text-amber-600" />
            Identified Technical Weaknesses
          </h3>
          <ul className="space-y-2">
            {report.weaknesses.map((wk, idx) => (
              <li key={idx} className="p-2.5 rounded-xl bg-amber-50/50 border border-amber-100 font-medium text-amber-900 flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-600 mt-1.5 flex-shrink-0"></span>
                <span>{wk}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Recommended Priorities */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-3">
        <h3 className="font-extrabold text-slate-900 text-sm border-b border-slate-100 pb-2">Strategic Priorities & Recommended Action Plan</h3>
        <div className="space-y-2">
          {report.recommendedPriorities.map((pri, idx) => (
            <div key={idx} className="p-3 rounded-xl bg-indigo-50/60 border border-indigo-100 font-bold text-indigo-900">
              {pri}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
