import React from 'react';
import { useApp } from '../../context/AppContext';
import { ShieldAlert, Check, X, ArrowRight, Layers } from 'lucide-react';

export const ApprovalsView: React.FC = () => {
  const { approvals, approveItem, rejectItem } = useApp();

  return (
    <div className="space-y-6">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-2xs">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">Pending Approvals Queue</h2>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-extrabold bg-amber-100 text-amber-800 dark:bg-amber-950/80 dark:text-amber-300">
              {approvals.length} Pending
            </span>
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Review and authorize autonomous AI agent modifications before applying live to production.
          </p>
        </div>
      </div>

      {/* Approvals Cards Queue */}
      <div className="space-y-4">
        {approvals.length === 0 ? (
          <div className="p-12 text-center bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl space-y-3">
            <ShieldAlert className="w-10 h-10 text-emerald-500 mx-auto" />
            <h3 className="font-bold text-slate-900 dark:text-white text-base">All Changes Approved!</h3>
            <p className="text-xs text-slate-500 max-w-sm mx-auto">
              There are currently no pending authorization requests from your AI Agent fleet.
            </p>
          </div>
        ) : (
          approvals.map((item) => (
            <div 
              key={item.id}
              className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-2xs space-y-4"
            >
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 pb-4 border-b border-slate-100 dark:border-slate-800">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-amber-50 dark:bg-amber-950/60 text-amber-600 dark:text-amber-400 flex items-center justify-center flex-shrink-0">
                    <ShieldAlert className="w-5 h-5 stroke-[2]" />
                  </div>
                  <div>
                    <h3 className="font-bold text-slate-900 dark:text-white text-base">{item.title}</h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400">
                      Generated by <strong className="text-indigo-600 dark:text-indigo-400">{item.agentName}</strong> • {item.timeAgo}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold ${
                    item.impact === 'High' ? 'bg-rose-50 text-rose-600 dark:bg-rose-950/80' : 'bg-amber-50 text-amber-600 dark:bg-amber-950/80'
                  }`}>
                    {item.impact} Impact
                  </span>
                </div>
              </div>

              <p className="text-xs text-slate-700 dark:text-slate-300 font-medium leading-relaxed">
                {item.details}
              </p>

              {/* Code / Content Diff Preview */}
              {item.diff && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 p-3 rounded-xl bg-slate-900 text-slate-200 font-mono text-[11px] overflow-x-auto">
                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-rose-400 uppercase tracking-wider">Before (Current Live)</p>
                    <div className="p-2 rounded bg-slate-950/80 text-rose-300 break-all">
                      - {item.diff.before}
                    </div>
                  </div>

                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider">After (Proposed by Agent)</p>
                    <div className="p-2 rounded bg-slate-950/80 text-emerald-300 break-all">
                      + {item.diff.after}
                    </div>
                  </div>
                </div>
              )}

              {/* Approval Actions */}
              <div className="flex items-center justify-end gap-3 pt-2">
                <button
                  onClick={() => rejectItem(item.id)}
                  className="px-4 py-2 rounded-xl border border-rose-200 dark:border-rose-800 bg-rose-50/40 hover:bg-rose-100 dark:bg-rose-950/40 dark:hover:bg-rose-900/60 text-rose-600 dark:text-rose-400 font-semibold text-xs transition-colors flex items-center gap-1.5 cursor-pointer"
                >
                  <X className="w-4 h-4" />
                  Reject Change
                </button>

                <button
                  onClick={() => approveItem(item.id)}
                  className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-xs transition-colors flex items-center gap-1.5 shadow-sm shadow-emerald-600/30 cursor-pointer"
                >
                  <Check className="w-4 h-4 stroke-[2.5]" />
                  Approve & Deploy Live
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
