import React from "react";
import { useApp } from "../../context/AppContext";
import { ShieldAlert, Check, X, ArrowRight, Layers } from "lucide-react";

export const ApprovalsView: React.FC = () => {
  const { approvals, approveItem, rejectItem } = useApp();

  return (
    <div className="space-y-6 animate-fade-in text-xs">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-5 rounded-2xl bg-white border border-slate-200/80 shadow-2xs">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-extrabold text-slate-900">
              Pending Approvals Queue
            </h2>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-extrabold bg-amber-100 text-amber-800 border border-amber-200">
              {approvals.length} Pending
            </span>
          </div>
          <p className="text-xs text-slate-500 font-medium mt-0.5">
            Review and authorize autonomous AI agent modifications before
            applying live to production.
          </p>
        </div>
      </div>

      {/* Approvals Cards Queue */}
      <div className="space-y-4">
        {approvals.length === 0 ? (
          <div className="p-12 text-center bg-white border border-slate-200/80 rounded-2xl shadow-2xs space-y-3">
            <ShieldAlert className="w-10 h-10 text-emerald-500 mx-auto" />
            <h3 className="font-extrabold text-slate-900 text-base">
              All Changes Approved!
            </h3>
            <p className="text-xs text-slate-500 font-medium max-w-sm mx-auto">
              There are currently no pending authorization requests from your AI
              Agent fleet.
            </p>
          </div>
        ) : (
          approvals.map((item) => (
            <div
              key={item.id}
              className="p-6 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-4"
            >
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 pb-4 border-b border-slate-100">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 border border-amber-200 flex items-center justify-center flex-shrink-0">
                    <ShieldAlert className="w-5 h-5 stroke-[2]" />
                  </div>
                  <div>
                    <h3 className="font-extrabold text-slate-900 text-base">
                      {item.title}
                    </h3>
                    <p className="text-xs text-slate-500 font-medium flex items-center gap-1.5 flex-wrap">
                      <span>Generated by</span>
                      <strong className="text-indigo-600 font-bold">
                        {item.agentName}
                      </strong>
                      <span>•</span>
                      <span>{item.timeAgo}</span>
                      {item.website && (
                        <>
                          <span>•</span>
                          <span className="inline-flex items-center px-2 py-0.5 rounded bg-slate-100 text-slate-600 border border-slate-200/80 font-bold text-[10px]">
                            Website: {item.website}
                          </span>
                        </>
                      )}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <span
                    className={`px-2.5 py-0.5 rounded-full text-xs font-extrabold border ${
                      item.impact === "High"
                        ? "bg-rose-50 text-rose-700 border-rose-200"
                        : "bg-amber-50 text-amber-800 border-amber-200"
                    }`}
                  >
                    {item.impact} Impact
                  </span>
                </div>
              </div>

              <p className="text-xs text-slate-700 font-medium leading-relaxed">
                {item.details}
              </p>

              {/* Code / Content Diff Preview - Clean White Mode */}
              {item.diff && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 p-3.5 rounded-xl bg-slate-50 border border-slate-200 font-mono text-[11px] overflow-x-auto">
                  <div className="space-y-1">
                    <p className="text-[10px] font-extrabold text-rose-700 uppercase tracking-wider">
                      Before (Current Live)
                    </p>
                    <div className="p-2.5 rounded-lg bg-rose-50/80 border border-rose-200/80 text-rose-900 font-bold break-all">
                      - {item.diff.before}
                    </div>
                  </div>

                  <div className="space-y-1">
                    <p className="text-[10px] font-extrabold text-emerald-700 uppercase tracking-wider">
                      After (Proposed by Agent)
                    </p>
                    <div className="p-2.5 rounded-lg bg-emerald-50/80 border border-emerald-200/80 text-emerald-900 font-bold break-all">
                      + {item.diff.after}
                    </div>
                  </div>
                </div>
              )}

              {/* Approval Actions */}
              <div className="flex items-center justify-end gap-3 pt-2 border-t border-slate-100">
                <button
                  onClick={() => rejectItem(item.id)}
                  className="px-4 py-2 rounded-xl border border-rose-200 bg-rose-50/60 hover:bg-rose-100 text-rose-700 font-bold text-xs transition-colors flex items-center gap-1.5 cursor-pointer"
                >
                  <X className="w-4 h-4" />
                  Reject Change
                </button>

                <button
                  onClick={() => approveItem(item.id)}
                  className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-xs transition-colors flex items-center gap-1.5 shadow-sm cursor-pointer"
                >
                  <Check className="w-4 h-4 stroke-[2.5]" />
                  Approve & Deploy Live
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
